import { Page, WireframeNode, NodeType, ElementOverride } from '@/types/schema';

function applyOverridesToCode(
  code: string,
  overrides: Record<string, ElementOverride>,
): string {
  let result = code;
  for (const [id, o] of Object.entries(overrides)) {
    const styleEntries: string[] = [];
    if (o.backgroundColor) styleEntries.push(`backgroundColor: '${o.backgroundColor}'`);
    if (o.color) styleEntries.push(`color: '${o.color}'`);
    if (o.fontSize) styleEntries.push(`fontSize: '${o.fontSize}'`);
    if (o.fontWeight) styleEntries.push(`fontWeight: '${o.fontWeight}'`);
    if (o.borderRadius) styleEntries.push(`borderRadius: '${o.borderRadius}'`);
    if (o.width) styleEntries.push(`width: '${o.width}'`);
    if (o.height) styleEntries.push(`height: '${o.height}'`);
    if (o.padding) styleEntries.push(`padding: '${o.padding}'`);

    if (styleEntries.length === 0 && !o.textContent) continue;

    const escaped = id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // Add style prop to elements with this data-unclash-id
    if (styleEntries.length > 0) {
      const styleValue = `{{ ${styleEntries.join(', ')} }}`;
      result = result.replace(
        new RegExp(`(data-unclash-id="${escaped}")(\\s|>)`, 'g'),
        `$1 style={${styleValue.slice(1, -1)}}$2`,
      );
    }
  }
  return result;
}

function generateCodeModeExport(pages: Page[]): Record<string, string> {
  const files: Record<string, string> = {};

  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    if (!page.code) continue;

    const overrides = page.elementOverrides ?? {};
    const code = applyOverridesToCode(page.code, overrides);

    // Wrap the App function in a proper React file
    const fileName = i === 0 ? 'src/app/page.tsx' : `src/app/${(page.name ?? `page-${i + 1}`).replace(/^\//, '').replace(/\//g, '-')}/page.tsx`;

    files[fileName] = `'use client';

${code}

export default App;
`;
  }

  files['src/app/layout.tsx'] = generateLayout();
  files['src/app/globals.css'] = `@import "tailwindcss";\n\n*, *::before, *::after { box-sizing: border-box; }\n`;
  files['package.json'] = generatePackageJson();
  files['tsconfig.json'] = generateTsConfig();
  files['postcss.config.mjs'] = `export default { plugins: { "@tailwindcss/postcss": {} } };\n`;
  files['README.md'] = `# Generated App\n\nGenerated by **Unclash** from a UI screenshot.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`;

  return files;
}

/**
 * Generates React + Tailwind code from page data.
 * - If a page has AI-generated code (page.code), that is used directly.
 * - Otherwise, falls back to the wireframe schema generator.
 * Returns a map of filename → file content.
 */
export function generateCode(pages: Page[]): Record<string, string> {
  const files: Record<string, string> = {};

  if (!pages.length) return files;

  // Code mode: export the AI-generated React component
  const codePage = pages.find((p) => p.code);
  if (codePage) {
    return generateCodeModeExport(pages);
  }

  // Collect unique component types from all pages (top-level nodes)
  const componentTypes = new Set<NodeType>();
  for (const p of pages) {
    for (const node of p.children) {
      componentTypes.add(node.type);
    }
  }

  // Generate individual component files
  for (const type of componentTypes) {
    const nodesOfType = pages.flatMap((p) => p.children).filter((n) => n.type === type);
    const componentName = getComponentName(type);
    files[`src/components/${componentName}.tsx`] = generateComponentFile(
      componentName,
      type,
      nodesOfType
    );
  }

  // Routes derived from pages whose name starts with "/"
  const routePages = pages
    .map((p) => ({ page: p, route: getRouteFromName(p.name) }))
    .filter((x) => x.route);

  // Decide home page:
  // - Prefer a page named "/" if present
  // - Else first page
  const explicitHome = pages.find((p) => (p.name || '').trim() === '/');
  const homePage = explicitHome || pages[0];

  // Generate nav links component if we have any route pages besides home
  const navRoutes = routePages
    .map((x) => x.route!)
    .filter((r) => r !== '/');
  if (navRoutes.length > 0) {
    files['src/components/NavLinks.tsx'] = generateNavLinks(navRoutes);
  }

  // Generate home page file
  files['src/app/page.tsx'] = generateMainPage(homePage, navRoutes.length > 0);

  // Generate route page files
  for (const { page: p, route } of routePages) {
    if (!route || route === '/') continue;
    const dir = routeToAppDir(route);
    files[`src/app/${dir}/page.tsx`] = generateMainPage(p, navRoutes.length > 0);
  }

  // Generate layout
  files['src/app/layout.tsx'] = generateLayout();

  // Generate globals.css
  files['src/app/globals.css'] = generateGlobalsCss();

  // Generate package.json
  files['package.json'] = generatePackageJson();

  // Generate README
  files['README.md'] = generateReadme();

  // Generate tsconfig
  files['tsconfig.json'] = generateTsConfig();

  // Generate tailwind + postcss config
  files['postcss.config.mjs'] = `export default { plugins: { "@tailwindcss/postcss": {} } };\n`;

  return files;
}

function getRouteFromName(name?: string): string | null {
  if (!name) return null;
  const trimmed = name.trim();
  if (!trimmed.startsWith('/')) return null;
  // Normalize to "/foo/bar" (no trailing slash unless root)
  if (trimmed === '/') return '/';
  return '/' + trimmed.replace(/^\/+/, '').replace(/\/+$/, '');
}

function routeToAppDir(route: string): string {
  const clean = route.replace(/^\/+/, '').replace(/\/+$/, '');
  // Basic safety: allow only url-ish segments
  const segments = clean.split('/').filter(Boolean).map((s) => s.replace(/[^a-zA-Z0-9-_]/g, ''));
  return segments.join('/');
}

function generateNavLinks(routes: string[]): string {
  const links = routes
    .map((r) => {
      const label = r;
      return `{ href: '${r}', label: '${label}' }`;
    })
    .join(',\n  ');

  return `import Link from 'next/link';

const links = [
  { href: '/', label: '/' },
  ${links}
];

export default function NavLinks() {
  return (
    <nav className="flex items-center gap-3 text-sm">
      {links.map((l) => (
        <Link
          key={l.href}
          href={l.href}
          className="text-gray-300 hover:text-white hover:underline underline-offset-4"
        >
          {l.label}
        </Link>
      ))}
    </nav>
  );
}
`;
}

function getComponentName(type: NodeType): string {
  const map: Record<NodeType, string> = {
    container: 'Container',
    sidebar: 'Sidebar',
    navbar: 'Navbar',
    card: 'Card',
    table: 'DataTable',
    chart: 'ChartPlaceholder',
    button: 'Button',
    input: 'Input',
    text: 'Text',
    'image-placeholder': 'ImagePlaceholder',
  };
  return map[type] || 'Block';
}

function getTailwindClasses(type: NodeType): string {
  const map: Record<NodeType, string> = {
    container: 'bg-gray-900 rounded-lg',
    sidebar: 'bg-gray-950 border-r border-gray-800 flex flex-col',
    navbar: 'bg-gray-900 border-b border-gray-800 flex items-center px-6',
    card: 'bg-gray-900 rounded-xl border border-gray-800 p-6',
    table: 'bg-gray-900 rounded-xl border border-gray-800 p-4 overflow-auto',
    chart: 'bg-gray-900 rounded-xl border border-gray-800 p-6 flex items-center justify-center',
    button: 'bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg px-4 py-2 text-sm font-medium transition-colors',
    input: 'bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-sm text-gray-300 placeholder-gray-500',
    text: 'text-gray-200',
    'image-placeholder': 'bg-gray-800 rounded-lg flex items-center justify-center text-gray-500',
  };
  return map[type] || 'bg-gray-900 rounded-lg';
}

function generateComponentFile(
  componentName: string,
  type: NodeType,
  nodes: WireframeNode[]
): string {
  const sampleNode = nodes[0];
  const classes = getTailwindClasses(type);

  if (type === 'table') {
    return `export default function ${componentName}() {
  return (
    <div className="${classes}">
      <h3 className="text-lg font-semibold text-gray-100 mb-4">${sampleNode.text || 'Data Table'}</h3>
      <table className="w-full text-sm text-left">
        <thead>
          <tr className="border-b border-gray-700">
            <th className="py-3 px-4 text-gray-400 font-medium">Name</th>
            <th className="py-3 px-4 text-gray-400 font-medium">Status</th>
            <th className="py-3 px-4 text-gray-400 font-medium">Amount</th>
          </tr>
        </thead>
        <tbody>
          {[
            { name: 'Item 1', status: 'Active', amount: '$120' },
            { name: 'Item 2', status: 'Pending', amount: '$85' },
            { name: 'Item 3', status: 'Complete', amount: '$340' },
          ].map((row, i) => (
            <tr key={i} className="border-b border-gray-800">
              <td className="py-3 px-4 text-gray-200">{row.name}</td>
              <td className="py-3 px-4 text-gray-300">{row.status}</td>
              <td className="py-3 px-4 text-gray-200">{row.amount}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
`;
  }

  if (type === 'chart') {
    return `export default function ${componentName}() {
  return (
    <div className="${classes}">
      <div className="w-full">
        <h3 className="text-lg font-semibold text-gray-100 mb-4">${sampleNode.text || 'Chart'}</h3>
        <div className="h-48 flex items-end gap-2">
          {[40, 65, 45, 80, 55, 70, 90, 60, 75, 50, 85, 95].map((h, i) => (
            <div
              key={i}
              className="flex-1 bg-indigo-500/30 rounded-t hover:bg-indigo-500/50 transition-colors"
              style={{ height: \`\${h}%\` }}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
`;
  }

  if (type === 'sidebar') {
    return `export default function ${componentName}() {
  const navItems = ['Overview', 'Analytics', 'Customers', 'Products', 'Settings'];

  return (
    <aside className="${classes} p-4">
      <h2 className="text-lg font-bold text-white mb-8 px-2">Dashboard</h2>
      <nav className="flex flex-col gap-1">
        {navItems.map((item, i) => (
          <a
            key={i}
            href="#"
            className={\`px-3 py-2 rounded-lg text-sm transition-colors \${
              i === 0
                ? 'bg-indigo-600/20 text-indigo-400'
                : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800'
            }\`}
          >
            {item}
          </a>
        ))}
      </nav>
    </aside>
  );
}
`;
  }

  if (type === 'navbar') {
    return `export default function ${componentName}() {
  return (
    <header className="${classes} justify-between">
      <input
        type="text"
        placeholder="Search..."
        className="bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-sm text-gray-300 placeholder-gray-500 w-72"
      />
      <div className="flex items-center gap-4">
        <button className="text-gray-400 hover:text-gray-200 text-sm">Notifications</button>
        <div className="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center text-white text-sm font-medium">
          U
        </div>
      </div>
    </header>
  );
}
`;
  }

  if (type === 'card') {
    // Generate multiple cards if available
    if (nodes.length > 1) {
      return `interface CardProps {
  title: string;
  value: string;
}

function CardItem({ title, value }: CardProps) {
  return (
    <div className="${classes}">
      <p className="text-sm text-gray-400 mb-1">{title}</p>
      <p className="text-2xl font-bold text-white">{value}</p>
    </div>
  );
}

const cards = [
${nodes.map((n) => {
  const lines = (n.text || 'Metric\n0').split('\n');
  return `  { title: '${lines[0]}', value: '${lines[1] || '0'}' },`;
}).join('\n')}
];

export default function ${componentName}() {
  return (
    <>
      {cards.map((card, i) => (
        <CardItem key={i} title={card.title} value={card.value} />
      ))}
    </>
  );
}
`;
    }
    const lines = (sampleNode.text || 'Metric\n0').split('\n');
    return `export default function ${componentName}() {
  return (
    <div className="${classes}">
      <p className="text-sm text-gray-400 mb-1">${lines[0]}</p>
      <p className="text-2xl font-bold text-white">${lines[1] || '0'}</p>
    </div>
  );
}
`;
  }

  // Generic fallback
  return `export default function ${componentName}({ children }: { children?: React.ReactNode }) {
  return (
    <div className="${classes}">
      ${sampleNode.text ? `<span>${sampleNode.text}</span>` : '{children}'}
    </div>
  );
}
`;
}

function generateMainPage(page: Page, includeNavLinks: boolean): string {
  const hasSidebar = page.children.some((n) => n.type === 'sidebar');
  const hasNavbar = page.children.some((n) => n.type === 'navbar');
  const contentNodes = page.children.filter(
    (n) => n.type !== 'sidebar' && n.type !== 'navbar'
  );

  const cards = contentNodes.filter((n) => n.type === 'card');
  const others = contentNodes.filter((n) => n.type !== 'card');

  const imports = new Set<string>();
  if (hasSidebar) imports.add("import Sidebar from '@/components/Sidebar';");
  if (hasNavbar) imports.add("import Navbar from '@/components/Navbar';");
  if (includeNavLinks) imports.add("import NavLinks from '@/components/NavLinks';");
  if (cards.length > 0) imports.add("import Card from '@/components/Card';");
  for (const node of others) {
    const name = getComponentName(node.type);
    imports.add(`import ${name} from '@/components/${name}';`);
  }

  const semanticHint = getPageSemanticHint(page);

  return `${Array.from(imports).join('\n')}

export default function ${semanticHint}Page() {
  return (
    <div className="flex h-screen bg-gray-950 text-white">
      ${hasSidebar ? '<Sidebar />' : ''}
      <div className="flex-1 flex flex-col overflow-hidden">
        ${hasNavbar ? '<Navbar />' : ''}
        ${includeNavLinks ? '<div className="px-6 py-3 border-b border-gray-800 bg-gray-950/40"><NavLinks /></div>' : ''}
        <main className="flex-1 overflow-auto p-6">
          ${
            cards.length > 0
              ? `<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-${Math.min(cards.length, 4)} gap-6 mb-6">
            <Card />
          </div>`
              : ''
          }
          ${
            others.length > 0
              ? `<div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            ${others.map((n) => `<${getComponentName(n.type)} />`).join('\n            ')}
          </div>`
              : ''
          }
        </main>
      </div>
    </div>
  );
}
`;
}

function getPageSemanticHint(page: Page): string {
  const semanticTypes = page.children
    .map((n) => (n.metadata?.semanticType as string) ?? n.type)
    .filter(Boolean);

  if (semanticTypes.includes('hero') || semanticTypes.includes('hero-content')) return 'Landing';
  if (semanticTypes.includes('sidebar') && semanticTypes.some((t) => t === 'chart' || t === 'stat-card' || t === 'metric-tile')) return 'Dashboard';
  if (semanticTypes.some((t) => t === 'product-card' || t === 'pricing-card')) return 'Catalog';
  if (semanticTypes.some((t) => t === 'form' || t === 'form-row')) return 'Settings';
  return 'Dashboard';
}

function generateLayout(): string {
  return `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated dashboard starter code',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
`;
}

function generateGlobalsCss(): string {
  return `@import "tailwindcss";

body {
  background-color: #030712;
  color: #f9fafb;
}
`;
}

function generatePackageJson(): string {
  return JSON.stringify(
    {
      name: 'generated-dashboard',
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
      },
      dependencies: {
        next: '^15.0.0',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
      },
      devDependencies: {
        '@tailwindcss/postcss': '^4',
        '@types/node': '^20',
        '@types/react': '^19',
        '@types/react-dom': '^19',
        tailwindcss: '^4',
        typescript: '^5',
      },
    },
    null,
    2
  );
}

function generateReadme(): string {
  return `# Generated Dashboard

This project was generated by **Unclash** from a dashboard screenshot wireframe.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) to view the dashboard.

## Stack

- **Next.js** (App Router)
- **React 19**
- **Tailwind CSS 4**
- **TypeScript**

## Structure

\`\`\`
src/
├── app/
│   ├── layout.tsx    # Root layout
│   ├── page.tsx      # Main dashboard page
│   └── globals.css   # Global styles
└── components/       # Reusable UI components
\`\`\`
`;
}

function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    },
    null,
    2
  );
}
